### ISSUE TITLE
Friendly Errors setup in utils.js causes crash

### ISSUE THREAD

**Issue by tutley** [vuetifyjs/webpack-advanced-old2#32]
I'm not sure if this is an issue or an enhancement, but I just thought I'd report that if you customize your webpack configuration (add a plugin, change a template, etc) and make a mistake, the Friendly Errors Plugin as configured in utils.js causes an error that is unrelated to your actual error. For example, I changed my development template to 'dev-index.html' but I had the variable in webpack.dev.conf.js set to 'index.html'. When I tried to npm run dev, I got:

```
/Users/uttles/go/src/bitbucket.org/uttles/foundirl/client/build/utils.js:95
    const filename = error.file.split('!').pop()
                               ^

TypeError: Cannot read property 'split' of undefined
    at FriendlyErrorsWebpackPlugin.onErrors (/Users/uttles/go/src/bitbucket.org/uttles/foundirl/client/build/utils.js:95:32)
```

I discovered the root of the problem by doing the following:
```
exports.createNotifierCallback = function() {
  const notifier = require('node-notifier')

  return (severity, errors) => {
    if (severity !== 'error') {
      return
    }
    const error = errors[0]
    console.log(JSON.stringify(error, null, 2))
    const filename = error.file.split('!').pop()
    notifier.notify({
      title: pkg.name,
      message: severity + ': ' + error.name,
      subtitle: filename || '',
      icon: path.join(__dirname, 'logo.png')
    })
  }
}

```

**Comment by maurop123** [comment]
Gotta delete this repo, but I've copied the issue text and will mention you @tutley when I remake the issue.
