### ISSUE TITLE
[Request]: Add eslint-plugin-vue

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/webpack-advanced-old2#36]
there are already commits in vuejs-templates/webpack:dev

**Comment by BoyardIsBack** [comment]
Even in master :)

**Comment by maurop123** [comment]
Am currently updating the webpack template with the latest from vuejs-templates/webpack. This is gona solve this issue. And I gotta delete this repo. Feel free to check if this plugin is on the new template after today.
